# https://github.com/yandex-cloud/fluent-bit-plugin-yandex/releases
FROM cr.yandex/yc/fluent-bit-plugin-yandex:v2.1.1-fluent-bit-2.1.7
COPY fluentbit.conf /fluent-bit/etc/fluent-bit.conf
COPY parsers.conf /fluent-bit/etc/parsers.conf
