services:
  myapp_service:
    container_name: myapp_container
    image: cr.yandex/$YC_REGISTRY_ID/myapp_image:v08
    restart: no
    ports:
      - "80:8080"
    volumes:
      - secrets_volume:/secrets
    depends_on:
      fluentbit_service:
        condition: service_healthy
      secrets_service:
        condition: service_completed_successfully
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: myapp_logging_tag
    environment:
      - VK_API_TOKEN_FILE=/secrets/VK_API_TOKEN
      - AWS_ACCESS_KEY_ID_FILE=/secrets/AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY_FILE=/secrets/AWS_SECRET_ACCESS_KEY
      - SETTINGS_PASSWORD_FILE=/secrets/SETTINGS_PASSWORD
      - S3_BUCKET=myapp2-bucket
      - S3_OBJECT_KEY=myapp2-settings

  secrets_service:
    container_name: secrets_container
    image: cr.yandex/$YC_REGISTRY_ID/secrets_image:v02
    restart: no
    network_mode: host
    volumes:
      - secrets_volume:/secrets
    environment:
      - YC_FOLDER_ID=$YC_FOLDER_ID
      - YC_SECRET_ID=$YC_SECRET_ID
      - SECRET_KEYS=VK_API_TOKEN AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY SETTINGS_PASSWORD
      - SECRETS_PATH=/secrets

  fluentbit_service:
    container_name: fluentbit_container
    image: cr.yandex/$YC_REGISTRY_ID/fluentbit_image:v02
    restart: no
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    healthcheck:
      test: ["CMD", "/bin/busybox", "wget", "-q", "-O", "/dev/null", "http://127.0.0.1:2020/api/v1/health"]
      timeout: 2s
      interval: 5s
      retries: 6
    environment:
      - YC_LOGGING_GROUP_ID=$YC_LOGGING_GROUP_ID

volumes:
  secrets_volume:
    driver: local
    driver_opts:
      type: none
      device: /dev/shm
      o: bind
